export interface CreateTrainComponentDto {
    name: string;
    uniqueNumber: string;
    canAssignQuantity: boolean;
    // Note: ID is not included as it's generated by the backend.
    // Initial quantity logic is handled by the backend service.
    quantity:number;
  }